__title__ = 'home_assistant_integrations'
__description__ = 'Custom Home Assistant Integrations'
__url__ = 'https://github.com/dskrypa/home_assistant_integrations'
__version__ = '2022.01.29-2'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2021 Doug Skrypa'
